# The absolute or relative path to the folder containing annotations/images
data_root = "datasets/crayfish_coco"

# Optional: Manual override if you don't want auto-detection
classes = ["crayfish"]

[train]
ann_file = "annotations/train.json"
img_dir = "train2017"

[val]
ann_file = "annotations/val.json"
img_dir = "val2017"

[test]
ann_file = "annotations/test.json"
img_dir = "test2017"
